### ISSUE TITLE
Make Failure On flx_run

### ISSUE THREAD

**Issue by fundamental** [felix-lang/felix#59]
'make build' fails on Slackware64 14.1 (ocaml 3.12.1, python 2.7.5, llvm/clang 3.5/3.3) 
I'm reasonably certain that this also occurs on the 32 bit version though it has been a while since I have checked.
Prior to this error, the build appears to be moving along smoothly besides the screens of warnings about the _start_switch label being unused.

It dies after appearing to compile all of the ML files as well as parsing through all the grammar files.

`*** Error in `build/release/host/bin/flx_run': munmap_chunk(): invalid pointer: 0x0000000002001340 ***`

From the resulting coredump:

```
#0  0x00007fe6a1ecddd9 in raise () from /lib64/libc.so.6
#1  0x00007fe6a1ecf4e8 in abort () from /lib64/libc.so.6
#2  0x00007fe6a1f0f6e7 in __libc_message () from /lib64/libc.so.6
#3  0x00007fe6a1f15837 in malloc_printerr () from /lib64/libc.so.6
#4  0x0000000000406633 in flx::gc::collector::malloc_free::deallocate (this=<optimized out>, p=0x2001340) at build/release/share/src/gc/flx_collector.cpp:34
#5  0x0000000000406cbc in flx::gc::collector::flx_collector_t::delete_frame (this=this@entry=0x19371d0, fp=<optimized out>) at build/release/share/src/gc/flx_collector.cpp:288
#6  0x0000000000406d07 in flx::gc::collector::flx_collector_t::reap (this=this@entry=0x19371d0) at build/release/share/src/gc/flx_collector.cpp:297
#7  0x0000000000406ece in flx::gc::collector::flx_collector_t::sweep (this=this@entry=0x19371d0) at build/release/share/src/gc/flx_collector.cpp:412
#8  0x00000000004073e6 in flx::gc::collector::flx_collector_t::impl_collect (this=0x19371d0) at build/release/share/src/gc/flx_collector.cpp:558
#9  0x0000000000407dfd in flx::gc::collector::flx_ts_collector_t::v_collect (this=<optimized out>) at build/release/share/src/gc/flx_ts_collector.cpp:21
#10 0x00007fe6a1634d04 in flx::gc::generic::collector_t::collect() () from build/release/host/lib/rtl/libflx_dynamic.so
#11 0x00007fe6a1421dfe in flx::gc::generic::gc_profile_t::actually_collect() () from build/release/host/lib/rtl/libflx_gc_dynamic.so
#12 0x00007fe6a1421d8d in flx::gc::generic::gc_profile_t::maybe_collect() () from build/release/host/lib/rtl/libflx_gc_dynamic.so
#13 0x00007fe6a1421fd4 in flx::gc::generic::gc_profile_t::allocate(flx::gc::generic::gc_shape_t const*, unsigned long, bool) () from build/release/host/lib/rtl/libflx_gc_dynamic.so
#14 0x00007fe6a142234b in operator new(unsigned long, flx::gc::generic::gc_profile_t&, flx::gc::generic::gc_shape_t const&, bool) () from build/release/host/lib/rtl/libflx_gc_dynamic.so
#15 0x00007fe6a1c681ac in flxusr::flx_build_prep::_lam_36125::resume (this=0x30bf030) at /home/mark/.felix/cache/text/home/mark/felix/src/tools/flx_build_prep.cpp:797
#16 0x0000000000405499 in flx::rtl::fthread_t::run (this=0x193b5a0) at build/release/share/src/rtl/flx_rtl.cpp:118
#17 0x0000000000404b0b in flx::run::sync_sched::frun (this=this@entry=0x193b698) at build/release/share/src/rtl/flx_sync.cpp:209
#18 0x0000000000405df2 in flx::run::async_sched::prun (this=0x193b660, block_flag=block_flag@entry=flx::run::async_sched::block) at build/release/share/src/rtl/flx_async_world.cpp:137
#19 0x0000000000403145 in flx::run::flx_world::run_until_complete (this=this@entry=0x1937080) at build/release/share/src/rtl/flx_world.cpp:303
#20 0x00000000004025cf in felix_run (argc=9, argv=0x7fffeb836e48) at build/release/share/src/flx_drivers/flx_run.include:335
#21 0x00000000004026e9 in main (argc=<optimized out>, argv=<optimized out>) at build/release/share/src/flx_drivers/flx_run_main.cxx:4
```

**Comment by skaller** [comment]
I have to close due to age. No idea if any issue here is resolved.
